trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: "Install NuGet"

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
  displayName: "Restore NuGet Packages"
- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    msbuildArchitecture: 'x64'
    configuration: 'Release'
  displayName: "Build Project"
- task: CopyFiles@2
  inputs:
    SourceFolder: ''
    Contents: '**/*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: "Copy Artifacts"
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: "Publish Artifacts"